# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project/ui/ui_main_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ascor(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 622)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(0, 21, 41, 255), stop:0.427447 rgba(0, 0, 0, 235), stop:1 rgba(0, 53, 102, 107));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_create_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create_file.setGeometry(QtCore.QRect(458, 578, 122, 31))
        self.pushButton_create_file.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(6, 176, 37, 255);\n"
"}")
        self.pushButton_create_file.setObjectName("pushButton_create_file")
        self.pushButton_down_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_down_file.setGeometry(QtCore.QRect(598, 578, 134, 31))
        self.pushButton_down_file.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(6, 176, 37, 255);\n"
"}")
        self.pushButton_down_file.setObjectName("pushButton_down_file")
        self.comboBox_system = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_system.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.comboBox_system.setStyleSheet("QComboBox {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"background-color: rgba(14, 77, 201, 255);\n"
"}\n"
"\n"
"QComboBox::item {\n"
"color: rgba(255, 255, 255, 255);\n"
"}")
        self.comboBox_system.setObjectName("comboBox_system")
        self.comboBox_system.addItem("")
        self.comboBox_system.addItem("")
        self.label_strem_text = QtWidgets.QLabel(self.centralwidget)
        self.label_strem_text.setGeometry(QtCore.QRect(570, 10, 121, 31))
        self.label_strem_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"font-size: 12pt;")
        self.label_strem_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_strem_text.setObjectName("label_strem_text")
        self.label_strem = QtWidgets.QLabel(self.centralwidget)
        self.label_strem.setGeometry(QtCore.QRect(680, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_strem.setFont(font)
        self.label_strem.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_strem.setAlignment(QtCore.Qt.AlignCenter)
        self.label_strem.setObjectName("label_strem")
        self.pushButton_down_form = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_down_form.setGeometry(QtCore.QRect(148, 578, 122, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_down_form.setFont(font)
        self.pushButton_down_form.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(6, 176, 37, 255);\n"
"}")
        self.pushButton_down_form.setObjectName("pushButton_down_form")
        self.pushButton_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_info.setGeometry(QtCore.QRect(8, 578, 122, 31))
        self.pushButton_info.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(14, 77, 201, 255);\n"
"}")
        self.pushButton_info.setObjectName("pushButton_info")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260, 721, 241))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("#tableWidget {\n"
"    background-image: url(:/images/img_2ekuEBFS8DXMU84PveV8 (1).png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QTableWidget::header {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 510, 721, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 80, 721, 131))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border-radius: 10px;\n"
"border: 3px solid  rgba(255, 255, 255, 150);")
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setStyleSheet("background-color: none;\n"
"border-radius: none;\n"
"border: none;")
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_col = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_col.setFont(font)
        self.label_col.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_col.setAlignment(QtCore.Qt.AlignCenter)
        self.label_col.setObjectName("label_col")
        self.horizontalLayout_4.addWidget(self.label_col)
        self.label_sr_ball = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily(".Andale Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_sr_ball.setFont(font)
        self.label_sr_ball.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_sr_ball.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sr_ball.setObjectName("label_sr_ball")
        self.horizontalLayout_4.addWidget(self.label_sr_ball)
        self.label_suc = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_suc.setFont(font)
        self.label_suc.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_suc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_suc.setObjectName("label_suc")
        self.horizontalLayout_4.addWidget(self.label_suc)
        self.verticalLayout_2.addWidget(self.frame1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: none;\n"
"border-radius: none;\n"
"border: none;")
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_col_current = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_col_current.setFont(font)
        self.label_col_current.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_col_current.setAlignment(QtCore.Qt.AlignCenter)
        self.label_col_current.setObjectName("label_col_current")
        self.horizontalLayout_3.addWidget(self.label_col_current)
        self.label_gpa = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(",Gill Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_gpa.setFont(font)
        self.label_gpa.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_gpa.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gpa.setObjectName("label_gpa")
        self.horizontalLayout_3.addWidget(self.label_gpa)
        self.label_secessful = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_secessful.setFont(font)
        self.label_secessful.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_secessful.setAlignment(QtCore.Qt.AlignCenter)
        self.label_secessful.setObjectName("label_secessful")
        self.horizontalLayout_3.addWidget(self.label_secessful)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 222, 721, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(6, 176, 37, 255);\n"
"}")
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_up = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_up.setFont(font)
        self.pushButton_up.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(6, 176, 37, 255);\n"
"}")
        self.pushButton_up.setObjectName("pushButton_up")
        self.horizontalLayout.addWidget(self.pushButton_up)
        self.pushButton_del = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(6, 176, 37, 255);\n"
"}")
        self.pushButton_del.setObjectName("pushButton_del")
        self.horizontalLayout.addWidget(self.pushButton_del)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"background-color: rgba(15, 15, 15, 150);\n"
"color: rgba(255, 255, 255, 255);\n"
"border: 1px solid rgba(255, 255, 255, 255);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgba(240, 17, 58, 255);\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_clear = QtWidgets.QLabel(self.centralwidget)
        self.label_clear.setGeometry(QtCore.QRect(70, 50, 61, 21))
        self.label_clear.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_clear.setObjectName("label_clear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_create_file.setText(_translate("MainWindow", "Создать файл"))
        self.pushButton_down_file.setText(_translate("MainWindow", "Загрузить файл"))
        self.comboBox_system.setItemText(0, _translate("MainWindow", "5-бальная система"))
        self.comboBox_system.setItemText(1, _translate("MainWindow", "10-бальная система"))
        self.label_strem_text.setText(_translate("MainWindow", "Стремимся к"))
        self.label_strem.setText(_translate("MainWindow", "0.0"))
        self.pushButton_down_form.setText(_translate("MainWindow", "Скачать форму"))
        self.pushButton_info.setText(_translate("MainWindow", "Подробнее"))
        self.label_col.setText(_translate("MainWindow", "0"))
        self.label_sr_ball.setText(_translate("MainWindow", "0.0"))
        self.label_suc.setText(_translate("MainWindow", "0"))
        self.label_col_current.setText(_translate("MainWindow", "Всего предметов"))
        self.label_gpa.setText(_translate("MainWindow", "Средний балл"))
        self.label_secessful.setText(_translate("MainWindow", "Удалось выполнить"))
        self.pushButton_add.setText(_translate("MainWindow", "Добавить предмет"))
        self.pushButton_up.setText(_translate("MainWindow", "Редактировать запись"))
        self.pushButton_del.setText(_translate("MainWindow", "Удалить предмет"))
        self.pushButton_clear.setText(_translate("MainWindow", "X"))
        self.label_clear.setText(_translate("MainWindow", "Очистить"))
